// ── Mock Data (Fallback for Offline/Development) ───────

const MOCK_SOURCES = [
  { id: 'reuters', name: 'Reuters', credibility: 0.95, status: 'healthy' },
  { id: 'ap', name: 'AP News', credibility: 0.95, status: 'healthy' },
  { id: 'bbc', name: 'BBC News', credibility: 0.90, status: 'healthy' },
  { id: 'nyt', name: 'New York Times', credibility: 0.88, status: 'healthy' },
  { id: 'ft', name: 'Financial Times', credibility: 0.92, status: 'healthy' },
  { id: 'guardian', name: 'The Guardian', credibility: 0.85, status: 'healthy' },
  { id: 'wsj', name: 'Wall Street Journal', credibility: 0.90, status: 'healthy' },
  { id: 'politico', name: 'Politico', credibility: 0.82, status: 'degraded' },
  { id: 'economist', name: 'The Economist', credibility: 0.91, status: 'healthy' },
  { id: 'wapo', name: 'Washington Post', credibility: 0.87, status: 'healthy' },
];

const MOCK_STORIES = [
  {
    id: '001',
    rank: 1,
    featured: true,
    headline: 'Federal Reserve holds interest rates steady amid inflation concerns',
    summary: 'The Fed voted unanimously to maintain the federal funds rate target range, citing persistent inflation and a resilient labor market.',
    repSource: MOCK_SOURCES[0],
    sourceCount: 11,
    confidence: 0.97,
    rankReason: 'High cross-source confirmation across 11 outlets. Breaking within last 90 minutes.',
    firstSeenAt: new Date(Date.now() - 95 * 60000).toISOString(),
    tags: ['economy', 'fed', 'rates'],
  },
  {
    id: '002',
    rank: 2,
    featured: false,
    headline: 'European parliament votes on landmark AI regulation package',
    summary: 'MEPs passed the AI Act with provisions covering high-risk systems, foundation models, and enforcement.',
    repSource: MOCK_SOURCES[2],
    sourceCount: 8,
    confidence: 0.91,
    rankReason: 'Strong international coverage. Confirmed by 8 credible outlets.',
    firstSeenAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    tags: ['tech', 'ai', 'europe'],
  },
  {
    id: '003',
    rank: 3,
    featured: false,
    headline: 'Ceasefire negotiations enter critical phase as mediators push for agreement',
    summary: 'Talks entering a decisive 48-hour window, with both parties under pressure.',
    repSource: MOCK_SOURCES[1],
    sourceCount: 14,
    confidence: 0.88,
    rankReason: 'Highest source count in feed. Geopolitical significance elevated.',
    firstSeenAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    tags: ['geopolitics', 'diplomacy'],
  },
  {
    id: '004',
    rank: 4,
    featured: false,
    headline: 'Major chipmaker announces $40B expansion of US semiconductor fabs',
    summary: 'Investment spanning three new facilities expected to create 20,000+ jobs.',
    repSource: MOCK_SOURCES[4],
    sourceCount: 7,
    confidence: 0.85,
    rankReason: 'Confirmed press release. Business and tech coverage aligned.',
    firstSeenAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    tags: ['tech', 'economy', 'manufacturing'],
  },
  {
    id: '005',
    rank: 5,
    featured: false,
    headline: 'Climate summit produces binding emissions framework for G20 nations',
    summary: 'G20 nations agreed to a legally binding emissions schedule with independent verification.',
    repSource: MOCK_SOURCES[5],
    sourceCount: 9,
    confidence: 0.82,
    rankReason: 'Wide international coverage. Some variance in framing across outlets.',
    firstSeenAt: new Date(Date.now() - 7 * 3600000).toISOString(),
    tags: ['climate', 'geopolitics', 'g20'],
  },
];

const SYSTEM_STATE = {
  missionStatus: 'green',
  lastRefresh: new Date(Date.now() - 2 * 60000).toISOString(),
  sourcesPolled: 47,
  healthySources: 44,
  failedSources: 3,
  ingestion: 'green',
  clustering: 'green',
  ranking: 'green',
  apiStatus: 'green',
};
